version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: "aws-sdk"
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "cdk-assets"
      - dependency-name: "constructs"
      - dependency-name: "@aws-cdk/*"
      - dependency-name: "puppeteer"
    labels:
      - npm dependencies
