version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: aws-cdk
      - dependency-name: aws-cdk-lib
      - dependency-name: constructs
    labels:
      - npm dependencies
