version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "aws-sdk"
      - dependency-name: "aws-cdk"
      - dependency-name: "aws-cdk-lib"
      - dependency-name: "cdk-assets"
      - dependency-name: "constructs"
      - dependency-name: "@aws-cdk/*"
    labels:
      - npm dependencies
