name: cdk-web CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: installing dependencies
        run: npm install

      - name: building the bundle
        run: npm run build

      - name: running unit tests
        run: npm test

      - id: check
        name: checking if we need to publish...
        uses: ./.github/workflows/composites/publishing

      - name: releasing on NPM (cdk-web - with dependencies)
        if: ${{ steps.check.outputs.publishing }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: releasing on NPM (aws-cdk-web - without dependencies)
        if: ${{ steps.check.outputs.publishing }}
        run: |
          rm -rf aws-cdk-web
          mkdir -p aws-cdk-web
          pushd aws-cdk-web
            npm init -y
            cp ../README.md ../LICENSE .
            cp ../dist/cdk-web.js index.js
            for key in license version description author; do
              npx --yes json -I -f package.json -e "this.$key=\"`node -p \"require('../package.json').$key\"`\""
            done
            for key in scripts keywords; do
              npx --yes json -I -f package.json -e "this.$key=undefined"
            done
            npm publish
          popd
          rm -rf aws-cdk-web
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: tagging a new release on Git
        if: ${{ steps.check.outputs.publishing }}
        uses: actions/github-script@v5
        with:
          script: |
            const { version } = require('./package.json');
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${ version }`,
              sha: context.sha
            })

      - name: version bump
        if: ${{ steps.check.outputs.publishing }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch --force -m "version bumped post-release"
          git push
