name: cdk-web CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  main:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.head_ref || github.ref }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: setup aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-cdk-web
          aws-region: us-east-1

      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: installing dependencies
        run: npm install

      - name: building the bundle
        run: PUBLIC_URL="https://3p3r.github.io/cdk-web" npm run build

      - name: nothing should be modified
        run: git diff --exit-code .

      - name: update homepage for npm
        run: npx --yes json -I -f package.json -e 'this.homepage="https://3p3r.github.io/cdk-web"'

      - name: running unit tests
        run: npm test

      - name: releasing on NPM (cdk-web - with dependencies)
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: releasing on NPM (aws-cdk-web - without dependencies)
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          rm -rf aws-cdk-web
          mkdir -p aws-cdk-web
          pushd aws-cdk-web
            npm init -y
            cp ../README.md ../LICENSE .
            cp ../dist/cdk-web.js index.js
            for key in license version description author homepage keywords repository bugs; do
              npx --yes json -I -f package.json -e "this.$key=\"`node -p \"require('../package.json').$key\"`\""
            done
            for key in scripts keywords; do
              npx --yes json -I -f package.json -e "this.$key=undefined"
            done
            npm publish
          popd
          rm -rf aws-cdk-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: tagging a new release on Git
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: actions/github-script@v5
        with:
          script: |
            const { version } = require('./package.json');
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/v${ version }`,
              sha: context.sha
            })

      - name: deploy playground
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: version bump
        if: ${{ !env.ACT && github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        run: |
          git pull
          npx --yes json -I -f package.json -e "this.homepage=\"\""
          npm version patch --force -m "version bumped post-release"
          git push
